# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\"\x9a\x01\n\x08WsPacket\x12\x15\n\rmajor_version\x18\x01 \x01(\r\x12\x15\n\rminor_version\x18\x02 \x01(\r\x12\x11\n\tdevice_id\x18\x03 \x01(\r\x12\x11\n\tmodule_id\x18\x04 \x01(\r\x12\x0b\n\x03\x63md\x18\x05 \x01(\r\x12\x0c\n\x04type\x18\x06 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x12\x11\n\tclient_id\x18\x08 \x01(\t\"\x1b\n\x0b\x43omResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\",\n\rComResWithInt\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"/\n\x10\x43omResWithDouble\x12\r\n\x05value\x18\x01 \x01(\x01\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"-\n\x10\x43omResWithString\x12\x0b\n\x03str\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"x\n\x0b\x43ommonParam\x12\x0f\n\x07hasAuto\x18\x01 \x01(\x08\x12\x11\n\tauto_mode\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x12\n\nmode_index\x18\x04 \x01(\x05\x12\r\n\x05index\x18\x05 \x01(\x05\x12\x16\n\x0e\x63ontinue_value\x18\x06 \x01(\x01*K\n\x0eWsMajorVersion\x12\x1c\n\x18WS_MAJOR_VERSION_UNKNOWN\x10\x00\x12\x1b\n\x17WS_MAJOR_VERSION_NUMBER\x10\x01*K\n\x0eWsMinorVersion\x12\x1c\n\x18WS_MINOR_VERSION_UNKNOWN\x10\x00\x12\x1b\n\x17WS_MINOR_VERSION_NUMBER\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WSMAJORVERSION']._serialized_start=464
  _globals['_WSMAJORVERSION']._serialized_end=539
  _globals['_WSMINORVERSION']._serialized_start=541
  _globals['_WSMINORVERSION']._serialized_end=616
  _globals['_WSPACKET']._serialized_start=15
  _globals['_WSPACKET']._serialized_end=169
  _globals['_COMRESPONSE']._serialized_start=171
  _globals['_COMRESPONSE']._serialized_end=198
  _globals['_COMRESWITHINT']._serialized_start=200
  _globals['_COMRESWITHINT']._serialized_end=244
  _globals['_COMRESWITHDOUBLE']._serialized_start=246
  _globals['_COMRESWITHDOUBLE']._serialized_end=293
  _globals['_COMRESWITHSTRING']._serialized_start=295
  _globals['_COMRESWITHSTRING']._serialized_end=340
  _globals['_COMMONPARAM']._serialized_start=342
  _globals['_COMMONPARAM']._serialized_end=462
# @@protoc_insertion_point(module_scope)
