# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: device.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'device.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\x1a\nbase.proto\"\x1d\n\x0cReqLensDefog\x12\r\n\x05state\x18\x01 \x01(\x05\"\x1f\n\x0eReqAutoCooling\x12\r\n\x05state\x18\x01 \x01(\x05\" \n\x0fReqAutoShutdown\x12\r\n\x05state\x18\x01 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'device_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQLENSDEFOG']._serialized_start=28
  _globals['_REQLENSDEFOG']._serialized_end=57
  _globals['_REQAUTOCOOLING']._serialized_start=59
  _globals['_REQAUTOCOOLING']._serialized_end=90
  _globals['_REQAUTOSHUTDOWN']._serialized_start=92
  _globals['_REQAUTOSHUTDOWN']._serialized_end=124
# @@protoc_insertion_point(module_scope)
