# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: focus.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='focus.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x66ocus.proto\"-\n\x18ReqManualSingleStepFocus\x12\x11\n\tdirection\x18\x01 \x01(\r\"*\n\x15ReqManualContinuFocus\x12\x11\n\tdirection\x18\x01 \x01(\r\"\x1b\n\x19ReqStopManualContinuFocus\"F\n\x12ReqNormalAutoFocus\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x10\n\x08\x63\x65nter_x\x18\x02 \x01(\r\x12\x10\n\x08\x63\x65nter_y\x18\x03 \x01(\r\"!\n\x11ReqAstroAutoFocus\x12\x0c\n\x04mode\x18\x01 \x01(\r\"\x17\n\x15ReqStopAstroAutoFocusb\x06proto3'
)




_REQMANUALSINGLESTEPFOCUS = _descriptor.Descriptor(
  name='ReqManualSingleStepFocus',
  full_name='ReqManualSingleStepFocus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='ReqManualSingleStepFocus.direction', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=60,
)


_REQMANUALCONTINUFOCUS = _descriptor.Descriptor(
  name='ReqManualContinuFocus',
  full_name='ReqManualContinuFocus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='direction', full_name='ReqManualContinuFocus.direction', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=104,
)


_REQSTOPMANUALCONTINUFOCUS = _descriptor.Descriptor(
  name='ReqStopManualContinuFocus',
  full_name='ReqStopManualContinuFocus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=133,
)


_REQNORMALAUTOFOCUS = _descriptor.Descriptor(
  name='ReqNormalAutoFocus',
  full_name='ReqNormalAutoFocus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='ReqNormalAutoFocus.mode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='center_x', full_name='ReqNormalAutoFocus.center_x', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='center_y', full_name='ReqNormalAutoFocus.center_y', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=205,
)


_REQASTROAUTOFOCUS = _descriptor.Descriptor(
  name='ReqAstroAutoFocus',
  full_name='ReqAstroAutoFocus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='ReqAstroAutoFocus.mode', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=240,
)


_REQSTOPASTROAUTOFOCUS = _descriptor.Descriptor(
  name='ReqStopAstroAutoFocus',
  full_name='ReqStopAstroAutoFocus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=265,
)

DESCRIPTOR.message_types_by_name['ReqManualSingleStepFocus'] = _REQMANUALSINGLESTEPFOCUS
DESCRIPTOR.message_types_by_name['ReqManualContinuFocus'] = _REQMANUALCONTINUFOCUS
DESCRIPTOR.message_types_by_name['ReqStopManualContinuFocus'] = _REQSTOPMANUALCONTINUFOCUS
DESCRIPTOR.message_types_by_name['ReqNormalAutoFocus'] = _REQNORMALAUTOFOCUS
DESCRIPTOR.message_types_by_name['ReqAstroAutoFocus'] = _REQASTROAUTOFOCUS
DESCRIPTOR.message_types_by_name['ReqStopAstroAutoFocus'] = _REQSTOPASTROAUTOFOCUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqManualSingleStepFocus = _reflection.GeneratedProtocolMessageType('ReqManualSingleStepFocus', (_message.Message,), {
  'DESCRIPTOR' : _REQMANUALSINGLESTEPFOCUS,
  '__module__' : 'focus_pb2'
  # @@protoc_insertion_point(class_scope:ReqManualSingleStepFocus)
  })
_sym_db.RegisterMessage(ReqManualSingleStepFocus)

ReqManualContinuFocus = _reflection.GeneratedProtocolMessageType('ReqManualContinuFocus', (_message.Message,), {
  'DESCRIPTOR' : _REQMANUALCONTINUFOCUS,
  '__module__' : 'focus_pb2'
  # @@protoc_insertion_point(class_scope:ReqManualContinuFocus)
  })
_sym_db.RegisterMessage(ReqManualContinuFocus)

ReqStopManualContinuFocus = _reflection.GeneratedProtocolMessageType('ReqStopManualContinuFocus', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPMANUALCONTINUFOCUS,
  '__module__' : 'focus_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopManualContinuFocus)
  })
_sym_db.RegisterMessage(ReqStopManualContinuFocus)

ReqNormalAutoFocus = _reflection.GeneratedProtocolMessageType('ReqNormalAutoFocus', (_message.Message,), {
  'DESCRIPTOR' : _REQNORMALAUTOFOCUS,
  '__module__' : 'focus_pb2'
  # @@protoc_insertion_point(class_scope:ReqNormalAutoFocus)
  })
_sym_db.RegisterMessage(ReqNormalAutoFocus)

ReqAstroAutoFocus = _reflection.GeneratedProtocolMessageType('ReqAstroAutoFocus', (_message.Message,), {
  'DESCRIPTOR' : _REQASTROAUTOFOCUS,
  '__module__' : 'focus_pb2'
  # @@protoc_insertion_point(class_scope:ReqAstroAutoFocus)
  })
_sym_db.RegisterMessage(ReqAstroAutoFocus)

ReqStopAstroAutoFocus = _reflection.GeneratedProtocolMessageType('ReqStopAstroAutoFocus', (_message.Message,), {
  'DESCRIPTOR' : _REQSTOPASTROAUTOFOCUS,
  '__module__' : 'focus_pb2'
  # @@protoc_insertion_point(class_scope:ReqStopAstroAutoFocus)
  })
_sym_db.RegisterMessage(ReqStopAstroAutoFocus)


# @@protoc_insertion_point(module_scope)
