# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: focus.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'focus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ocus.proto\"-\n\x18ReqManualSingleStepFocus\x12\x11\n\tdirection\x18\x01 \x01(\r\"*\n\x15ReqManualContinuFocus\x12\x11\n\tdirection\x18\x01 \x01(\r\"\x1b\n\x19ReqStopManualContinuFocus\"F\n\x12ReqNormalAutoFocus\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x10\n\x08\x63\x65nter_x\x18\x02 \x01(\r\x12\x10\n\x08\x63\x65nter_y\x18\x03 \x01(\r\"!\n\x11ReqAstroAutoFocus\x12\x0c\n\x04mode\x18\x01 \x01(\r\"\x17\n\x15ReqStopAstroAutoFocusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'focus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQMANUALSINGLESTEPFOCUS']._serialized_start=15
  _globals['_REQMANUALSINGLESTEPFOCUS']._serialized_end=60
  _globals['_REQMANUALCONTINUFOCUS']._serialized_start=62
  _globals['_REQMANUALCONTINUFOCUS']._serialized_end=104
  _globals['_REQSTOPMANUALCONTINUFOCUS']._serialized_start=106
  _globals['_REQSTOPMANUALCONTINUFOCUS']._serialized_end=133
  _globals['_REQNORMALAUTOFOCUS']._serialized_start=135
  _globals['_REQNORMALAUTOFOCUS']._serialized_end=205
  _globals['_REQASTROAUTOFOCUS']._serialized_start=207
  _globals['_REQASTROAUTOFOCUS']._serialized_end=240
  _globals['_REQSTOPASTROAUTOFOCUS']._serialized_start=242
  _globals['_REQSTOPASTROAUTOFOCUS']._serialized_end=265
# @@protoc_insertion_point(module_scope)
