# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: panorama.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'panorama.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epanorama.proto\"\x18\n\x16ReqStartPanoramaByGrid\"F\n\x1cReqStartPanoramaByEulerRange\x12\x11\n\tyaw_range\x18\x01 \x01(\x02\x12\x13\n\x0bpitch_range\x18\x02 \x01(\x02\"\x94\x01\n\x1cReqStartPanoramaStitchUpload\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62usi_no\x18\x02 \x01(\t\x12\x14\n\x0c\x61pp_platform\x18\x03 \x01(\x05\x12\x15\n\rpanorama_name\x18\x04 \x01(\t\x12\n\n\x02\x61k\x18\x05 \x01(\t\x12\n\n\x02sk\x18\x06 \x01(\t\x12\r\n\x05token\x18\x07 \x01(\t\"\x11\n\x0fReqStopPanorama\"\x1d\n\x1bReqStopPanoramaStitchUpload\"\x81\x01\n%ResNotifyPanoramaStitchUploadComplete\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62usi_no\x18\x02 \x01(\t\x12\x15\n\rpanorama_name\x18\x03 \x01(\t\x12\x0b\n\x03mac\x18\x04 \x01(\t\x12\x12\n\nupload_res\x18\x05 \x01(\x08\"\xa3\x01\n$ResNotifyPanoramaCompressionProgress\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62usi_no\x18\x02 \x01(\t\x12\x15\n\rpanorama_name\x18\x03 \x01(\t\x12\x0b\n\x03mac\x18\x04 \x01(\t\x12\x17\n\x0ftotal_files_num\x18\x05 \x01(\r\x12\x1c\n\x14\x63ompressed_files_num\x18\x06 \x01(\r\"\x92\x01\n\x1fResNotifyPanoramaUploadProgress\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07\x62usi_no\x18\x02 \x01(\t\x12\x15\n\rpanorama_name\x18\x03 \x01(\t\x12\x0b\n\x03mac\x18\x04 \x01(\t\x12\x12\n\ntotal_size\x18\x05 \x01(\x04\x12\x15\n\ruploaded_size\x18\x06 \x01(\x04\"\xdd\x01\n\x17ResGetStitchUploadState\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0f\n\x07\x62usi_no\x18\x03 \x01(\t\x12\x15\n\rpanorama_name\x18\x04 \x01(\t\x12\x0b\n\x03mac\x18\x05 \x01(\t\x12\x17\n\x0ftotal_files_num\x18\x06 \x01(\r\x12\x1c\n\x14\x63ompressed_files_num\x18\x07 \x01(\r\x12\x12\n\ntotal_size\x18\x08 \x01(\x04\x12\x15\n\ruploaded_size\x18\t \x01(\x04\x12\x0c\n\x04step\x18\n \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'panorama_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQSTARTPANORAMABYGRID']._serialized_start=18
  _globals['_REQSTARTPANORAMABYGRID']._serialized_end=42
  _globals['_REQSTARTPANORAMABYEULERRANGE']._serialized_start=44
  _globals['_REQSTARTPANORAMABYEULERRANGE']._serialized_end=114
  _globals['_REQSTARTPANORAMASTITCHUPLOAD']._serialized_start=117
  _globals['_REQSTARTPANORAMASTITCHUPLOAD']._serialized_end=265
  _globals['_REQSTOPPANORAMA']._serialized_start=267
  _globals['_REQSTOPPANORAMA']._serialized_end=284
  _globals['_REQSTOPPANORAMASTITCHUPLOAD']._serialized_start=286
  _globals['_REQSTOPPANORAMASTITCHUPLOAD']._serialized_end=315
  _globals['_RESNOTIFYPANORAMASTITCHUPLOADCOMPLETE']._serialized_start=318
  _globals['_RESNOTIFYPANORAMASTITCHUPLOADCOMPLETE']._serialized_end=447
  _globals['_RESNOTIFYPANORAMACOMPRESSIONPROGRESS']._serialized_start=450
  _globals['_RESNOTIFYPANORAMACOMPRESSIONPROGRESS']._serialized_end=613
  _globals['_RESNOTIFYPANORAMAUPLOADPROGRESS']._serialized_start=616
  _globals['_RESNOTIFYPANORAMAUPLOADPROGRESS']._serialized_end=762
  _globals['_RESGETSTITCHUPLOADSTATE']._serialized_start=765
  _globals['_RESGETSTITCHUPLOADSTATE']._serialized_end=986
# @@protoc_insertion_point(module_scope)
