# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: param.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'param.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bparam.proto\x12\x05param\"?\n\x0eReqSetExposure\x12\x10\n\x08param_id\x18\x01 \x01(\x04\x12\x0c\n\x04mode\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\";\n\nReqSetGain\x12\x10\n\x08param_id\x18\x01 \x01(\x04\x12\x0c\n\x04mode\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"9\n\x08ReqSetWb\x12\x10\n\x08param_id\x18\x01 \x01(\x04\x12\x0c\n\x04mode\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x05\"8\n\x15ReqSetGeneralIntParam\x12\x10\n\x08param_id\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x05\":\n\x17ReqSetGeneralFloatParam\x12\x10\n\x08param_id\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x02\":\n\x17ReqSetGeneralBoolParams\x12\x10\n\x08param_id\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x08\"N\n\x0fReqSetAutoParam\x12\x13\n\x0b\x63\x61mera_type\x18\x01 \x01(\x05\x12\x15\n\rshooting_tech\x18\x02 \x01(\x05\x12\x0f\n\x07is_auto\x18\x03 \x01(\x08\"\x87\x01\n\x0fResSetAutoParam\x12\x15\n\rshooting_mode\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61mera_type\x18\x02 \x01(\x05\x12\x15\n\rshooting_tech\x18\x03 \x01(\x05\x12\x0f\n\x07is_auto\x18\x04 \x01(\x08\x12\x12\n\nupdate_all\x18\x05 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x06 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQSETEXPOSURE']._serialized_start=22
  _globals['_REQSETEXPOSURE']._serialized_end=85
  _globals['_REQSETGAIN']._serialized_start=87
  _globals['_REQSETGAIN']._serialized_end=146
  _globals['_REQSETWB']._serialized_start=148
  _globals['_REQSETWB']._serialized_end=205
  _globals['_REQSETGENERALINTPARAM']._serialized_start=207
  _globals['_REQSETGENERALINTPARAM']._serialized_end=263
  _globals['_REQSETGENERALFLOATPARAM']._serialized_start=265
  _globals['_REQSETGENERALFLOATPARAM']._serialized_end=323
  _globals['_REQSETGENERALBOOLPARAMS']._serialized_start=325
  _globals['_REQSETGENERALBOOLPARAMS']._serialized_end=383
  _globals['_REQSETAUTOPARAM']._serialized_start=385
  _globals['_REQSETAUTOPARAM']._serialized_end=463
  _globals['_RESSETAUTOPARAM']._serialized_start=466
  _globals['_RESSETAUTOPARAM']._serialized_end=601
# @@protoc_insertion_point(module_scope)
