# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rgb.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trgb.proto\"\x0c\n\nReqOpenRgb\"\r\n\x0bReqCloseRgb\"\x0e\n\x0cReqPowerDown\"\x11\n\x0fReqOpenPowerInd\"\x12\n\x10ReqClosePowerInd\"\x0b\n\tReqRebootb\x06proto3'
)




_REQOPENRGB = _descriptor.Descriptor(
  name='ReqOpenRgb',
  full_name='ReqOpenRgb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=25,
)


_REQCLOSERGB = _descriptor.Descriptor(
  name='ReqCloseRgb',
  full_name='ReqCloseRgb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=40,
)


_REQPOWERDOWN = _descriptor.Descriptor(
  name='ReqPowerDown',
  full_name='ReqPowerDown',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=56,
)


_REQOPENPOWERIND = _descriptor.Descriptor(
  name='ReqOpenPowerInd',
  full_name='ReqOpenPowerInd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=75,
)


_REQCLOSEPOWERIND = _descriptor.Descriptor(
  name='ReqClosePowerInd',
  full_name='ReqClosePowerInd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=95,
)


_REQREBOOT = _descriptor.Descriptor(
  name='ReqReboot',
  full_name='ReqReboot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ReqOpenRgb'] = _REQOPENRGB
DESCRIPTOR.message_types_by_name['ReqCloseRgb'] = _REQCLOSERGB
DESCRIPTOR.message_types_by_name['ReqPowerDown'] = _REQPOWERDOWN
DESCRIPTOR.message_types_by_name['ReqOpenPowerInd'] = _REQOPENPOWERIND
DESCRIPTOR.message_types_by_name['ReqClosePowerInd'] = _REQCLOSEPOWERIND
DESCRIPTOR.message_types_by_name['ReqReboot'] = _REQREBOOT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqOpenRgb = _reflection.GeneratedProtocolMessageType('ReqOpenRgb', (_message.Message,), {
  'DESCRIPTOR' : _REQOPENRGB,
  '__module__' : 'rgb_pb2'
  # @@protoc_insertion_point(class_scope:ReqOpenRgb)
  })
_sym_db.RegisterMessage(ReqOpenRgb)

ReqCloseRgb = _reflection.GeneratedProtocolMessageType('ReqCloseRgb', (_message.Message,), {
  'DESCRIPTOR' : _REQCLOSERGB,
  '__module__' : 'rgb_pb2'
  # @@protoc_insertion_point(class_scope:ReqCloseRgb)
  })
_sym_db.RegisterMessage(ReqCloseRgb)

ReqPowerDown = _reflection.GeneratedProtocolMessageType('ReqPowerDown', (_message.Message,), {
  'DESCRIPTOR' : _REQPOWERDOWN,
  '__module__' : 'rgb_pb2'
  # @@protoc_insertion_point(class_scope:ReqPowerDown)
  })
_sym_db.RegisterMessage(ReqPowerDown)

ReqOpenPowerInd = _reflection.GeneratedProtocolMessageType('ReqOpenPowerInd', (_message.Message,), {
  'DESCRIPTOR' : _REQOPENPOWERIND,
  '__module__' : 'rgb_pb2'
  # @@protoc_insertion_point(class_scope:ReqOpenPowerInd)
  })
_sym_db.RegisterMessage(ReqOpenPowerInd)

ReqClosePowerInd = _reflection.GeneratedProtocolMessageType('ReqClosePowerInd', (_message.Message,), {
  'DESCRIPTOR' : _REQCLOSEPOWERIND,
  '__module__' : 'rgb_pb2'
  # @@protoc_insertion_point(class_scope:ReqClosePowerInd)
  })
_sym_db.RegisterMessage(ReqClosePowerInd)

ReqReboot = _reflection.GeneratedProtocolMessageType('ReqReboot', (_message.Message,), {
  'DESCRIPTOR' : _REQREBOOT,
  '__module__' : 'rgb_pb2'
  # @@protoc_insertion_point(class_scope:ReqReboot)
  })
_sym_db.RegisterMessage(ReqReboot)


# @@protoc_insertion_point(module_scope)
