# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rgb.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'rgb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trgb.proto\"\x0c\n\nReqOpenRgb\"\r\n\x0bReqCloseRgb\"\x0e\n\x0cReqPowerDown\"\x11\n\x0fReqOpenPowerInd\"\x12\n\x10ReqClosePowerInd\"\x0b\n\tReqRebootb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rgb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQOPENRGB']._serialized_start=13
  _globals['_REQOPENRGB']._serialized_end=25
  _globals['_REQCLOSERGB']._serialized_start=27
  _globals['_REQCLOSERGB']._serialized_end=40
  _globals['_REQPOWERDOWN']._serialized_start=42
  _globals['_REQPOWERDOWN']._serialized_end=56
  _globals['_REQOPENPOWERIND']._serialized_start=58
  _globals['_REQOPENPOWERIND']._serialized_end=75
  _globals['_REQCLOSEPOWERIND']._serialized_start=77
  _globals['_REQCLOSEPOWERIND']._serialized_end=95
  _globals['_REQREBOOT']._serialized_start=97
  _globals['_REQREBOOT']._serialized_end=108
# @@protoc_insertion_point(module_scope)
