syntax = "proto3";

message ReqSetTime {
    uint64 timestamp = 1;
    double timezone_offset = 2;
}

message ReqSetTimezone {
    string timezone = 1;
}

message ReqSetMtpMode {
    int32 mode = 1;
}

message ReqSetCpuMode {
    int32 mode = 1;
}

message ReqsetMasterLock {
    bool lock = 1;
}

message ReqSetLowTempProtectionMode {
    int32 mode = 1;
}

message ReqSetLocation {
    double latitude = 1;
    double longitude = 2;
    double altitude = 3;
    string country_region = 4;
    string province = 5;
    string city = 6;
    string district = 7;
    bool enable = 8;
}
