# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\"8\n\nReqSetTime\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x17\n\x0ftimezone_offset\x18\x02 \x01(\x01\"\"\n\x0eReqSetTimezone\x12\x10\n\x08timezone\x18\x01 \x01(\t\"\x1d\n\rReqSetMtpMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\"\x1d\n\rReqSetCpuMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\" \n\x10ReqsetMasterLock\x12\x0c\n\x04lock\x18\x01 \x01(\x08\"+\n\x1bReqSetLowTempProtectionMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\"\xa1\x01\n\x0eReqSetLocation\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x10\n\x08\x61ltitude\x18\x03 \x01(\x01\x12\x16\n\x0e\x63ountry_region\x18\x04 \x01(\t\x12\x10\n\x08province\x18\x05 \x01(\t\x12\x0c\n\x04\x63ity\x18\x06 \x01(\t\x12\x10\n\x08\x64istrict\x18\x07 \x01(\t\x12\x0e\n\x06\x65nable\x18\x08 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQSETTIME']._serialized_start=16
  _globals['_REQSETTIME']._serialized_end=72
  _globals['_REQSETTIMEZONE']._serialized_start=74
  _globals['_REQSETTIMEZONE']._serialized_end=108
  _globals['_REQSETMTPMODE']._serialized_start=110
  _globals['_REQSETMTPMODE']._serialized_end=139
  _globals['_REQSETCPUMODE']._serialized_start=141
  _globals['_REQSETCPUMODE']._serialized_end=170
  _globals['_REQSETMASTERLOCK']._serialized_start=172
  _globals['_REQSETMASTERLOCK']._serialized_end=204
  _globals['_REQSETLOWTEMPPROTECTIONMODE']._serialized_start=206
  _globals['_REQSETLOWTEMPPROTECTIONMODE']._serialized_end=249
  _globals['_REQSETLOCATION']._serialized_start=252
  _globals['_REQSETLOCATION']._serialized_end=413
# @@protoc_insertion_point(module_scope)
